version: '3'
services:

  # application (code)
  php:
    build:
      context: ""
      dockerfile: app.dockerfile
    working_dir: /app
    volumes:
      - ${PROJECT_DIR}:/app
    networks:
      - backend

  # http server
  nginx:
    build:
      context: ""
      dockerfile: web.dockerfile
    working_dir: /app
    networks:
      - backend
    ports:
      - 777:80

networks:
  backend:
    driver: "bridge"
