version: '3'
services:

  # application (code)
  php:
    build:
      context: ""
      dockerfile: app.dockerfile
    working_dir: /app
    volumes:
      - ${PROJECT_DIR}:/app
    networks:
      - backend

  # http server

networks:
  backend:
    driver: "bridge"
